dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- node
before_script:
- npm install --legacy-peer-deps
script:
- 'set -eo pipefail;
   if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
     npm run test:travis;
   else
     npm run unit:coveralls;
   fi'
